name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        ghcr.io/${{ github.repository_owner }}/awesome-recipe-book--2026-andreasrg-edition:latest
        docker build -t $IMAGE_NAME .

    # Optional: add pytest here

    - name: Push Docker image (only on main)
      if: github.ref == 'refs/heads/main'
      run: |
        ghcr.io/${{ github.repository_owner }}/awesome-recipe-book--2026-andreasrg-edition:latest
        docker push $IMAGE_NAME
